title: Zod Docs
logo: logo.png
remote_theme: pmarsceill/just-the-docs
permalink: pretty

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

defaults:
    - scope:
          path: "docs/*"
      values:
          permalink: /:basename
          #   permalink: /:basename/
          #   permalink: :path/../:basename
#
# plugins:

# info:
#   default_layouts:
#     - home
#     - page
#     - post?
